language: c
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libfdk-aac-dev

script: ./bootstrap && ./configure && make
